//Inicio del código Interfaz Login
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author TOFIT
 */
public class Login extends javax.swing.JFrame {


    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        UsuarioLog = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        InicioSesion = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ContraseñaName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Contraseña = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JPanel();
        logintxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Brody.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 490));

        UsuarioLog.setBackground(new java.awt.Color(255, 255, 255));

        Logo.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.PNG"))); // NOI18N
        Logo.setText("BRODY");

        InicioSesion.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        InicioSesion.setText("INICIAR SESIÓN");

        Usuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Usuario.setText("USUARIO");

        CampoUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CampoUsuario.setForeground(new java.awt.Color(204, 204, 204));
        CampoUsuario.setText("Ingrese su nombre de usuario");
        CampoUsuario.setBorder(null);
        CampoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CampoUsuarioMousePressed(evt);
            }
        });
        CampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuarioActionPerformed(evt);
            }
        });

        ContraseñaName.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ContraseñaName.setText("CONTRASEÑA");

        Contraseña.setForeground(new java.awt.Color(204, 204, 204));
        Contraseña.setText("Contraseña");
        Contraseña.setBorder(null);
        Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContraseñaMousePressed(evt);
            }
        });
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });

        LoginBtn.setBackground(new java.awt.Color(191, 6, 6));

        logintxt.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        logintxt.setForeground(new java.awt.Color(255, 255, 255));
        logintxt.setText("      INGRESAR");
        logintxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logintxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logintxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logintxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logintxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginBtnLayout = new javax.swing.GroupLayout(LoginBtn);
        LoginBtn.setLayout(LoginBtnLayout);
        LoginBtnLayout.setHorizontalGroup(
            LoginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logintxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
        LoginBtnLayout.setVerticalGroup(
            LoginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logintxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout UsuarioLogLayout = new javax.swing.GroupLayout(UsuarioLog);
        UsuarioLog.setLayout(UsuarioLogLayout);
        UsuarioLogLayout.setHorizontalGroup(
            UsuarioLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(UsuarioLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuarioLogLayout.createSequentialGroup()
                        .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UsuarioLogLayout.createSequentialGroup()
                        .addGroup(UsuarioLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(ContraseñaName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(UsuarioLogLayout.createSequentialGroup()
                                .addGroup(UsuarioLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UsuarioLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1)
                                        .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InicioSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CampoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addGap(11, 11, 11))))
        );
        UsuarioLogLayout.setVerticalGroup(
            UsuarioLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InicioSesion)
                .addGap(18, 18, 18)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContraseñaName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(UsuarioLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 270, 490));

        pack();
    }// </editor-fold>                        

    private void CampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void logintxtMouseEntered(java.awt.event.MouseEvent evt) {                                      
    LoginBtn.setBackground(new Color(191, 6, 6));
    }                                     

    private void logintxtMouseExited(java.awt.event.MouseEvent evt) {                                     
    LoginBtn.setBackground(new Color(220,20,20)); 
    }                                    

    private void CampoUsuarioMousePressed(java.awt.event.MouseEvent evt) {                                          
     if (CampoUsuario.getText().equals("Ingrese su nombre de usuario")){
     CampoUsuario.setText("");
     CampoUsuario.setForeground(Color.black);
     }
     if(String.valueOf(Contraseña.getPassword()).isEmpty()){
     Contraseña.setText("**********");
     Contraseña.setForeground(Color.gray);
     }
    }                                         

    private void ContraseñaMousePressed(java.awt.event.MouseEvent evt) {                                        
     if (String.valueOf(Contraseña.getPassword()).equals("**********")){
     Contraseña.setText("");
     Contraseña.setForeground(Color.black);
     }
      if (Contraseña.getText().isEmpty()){
     CampoUsuario.setText("Ingrese su nombre de usuario");
     CampoUsuario.setForeground(Color.gray);
     }
    }                                       

    private void logintxtMouseClicked(java.awt.event.MouseEvent evt) {                                      
       
        String User1="Johan";
        String Clave1="12345";
     
        String Pass=new String(Contraseña.getPassword());
        
        if(CampoUsuario.getText().equals(User1)&&Pass.equals(Clave1)){
            MenuCuentas mc=new MenuCuentas();
            mc.setVisible(true);
            dispose();
        }else{
        JOptionPane.showMessageDialog(this," Usuario o Contraseña Incorrecta");
        }
        
    }                                     
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel ContraseñaName;
    private javax.swing.JLabel InicioSesion;
    private javax.swing.JPanel LoginBtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel UsuarioLog;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logintxt;
    // End of variables declaration                   
}
