/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Random;

/**
 *
 * @author TOFIT
 */
public class MenuCuentas extends javax.swing.JFrame {

    /**
     * Creates new form Cuentas
     */
    public MenuCuentas() {
        initComponents();
Cuentas c= new Cuentas();
        c.setSize(840, 600);
        c.setLocation(0, 0);
        
        Contenido1.removeAll();
        Contenido1.add(c, BorderLayout.CENTER);
        Contenido1.revalidate();
        Contenido1.repaint();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        InterfazPrimaria = new javax.swing.JPanel();
        PlazoFijo = new javax.swing.JButton();
        Prestamos = new javax.swing.JButton();
        Cuentas = new javax.swing.JButton();
        IconUser = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        Contenido1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Cuentas1 = new javax.swing.JPanel();
        Corriente = new javax.swing.JPanel();
        IconCorriente = new javax.swing.JLabel();
        CC = new javax.swing.JLabel();
        SaldoD = new javax.swing.JLabel();
        Ahorros = new javax.swing.JPanel();
        IconAhorros = new javax.swing.JLabel();
        CA = new javax.swing.JLabel();
        SaldoA = new javax.swing.JLabel();
        TarjetaCredito = new javax.swing.JPanel();
        IconCreditCard = new javax.swing.JLabel();
        TC = new javax.swing.JLabel();
        SaldoTC = new javax.swing.JLabel();
        Transferencias = new javax.swing.JPanel();
        Transferenciastxt = new javax.swing.JLabel();
        TransferenciasInt = new javax.swing.JPanel();
        Internacionales = new javax.swing.JButton();
        TransferenciasNac = new javax.swing.JPanel();
        Nacionales = new javax.swing.JButton();
        PagoLinea = new javax.swing.JPanel();
        Pago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InterfazPrimaria.setBackground(new java.awt.Color(255, 255, 255));
        InterfazPrimaria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlazoFijo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlazoFijo.setForeground(new java.awt.Color(200, 0, 0));
        PlazoFijo.setText("Plazo Fijo");
        PlazoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlazoFijoActionPerformed(evt);
            }
        });
        InterfazPrimaria.add(PlazoFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 280, 50));

        Prestamos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Prestamos.setForeground(new java.awt.Color(204, 0, 0));
        Prestamos.setText("Préstamos");
        Prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestamosActionPerformed(evt);
            }
        });
        InterfazPrimaria.add(Prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 280, 50));

        Cuentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cuentas.setForeground(new java.awt.Color(204, 0, 0));
        Cuentas.setText("Cuentas");
        Cuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CuentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CuentasMouseExited(evt);
            }
        });
        Cuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentasActionPerformed(evt);
            }
        });
        InterfazPrimaria.add(Cuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 50));

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconUseer.PNG"))); // NOI18N
        IconUser.setText("IconUser");
        InterfazPrimaria.add(IconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 110));

        Bienvenido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bienvenido.setText("Bienvenido,");
        InterfazPrimaria.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 20));

        NombreUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        NombreUsuario.setText("Pillajo De La Cruz Johan Ariel");
        InterfazPrimaria.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 230, 40));

        Contenido1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cuentas1.setBackground(new java.awt.Color(204, 204, 204));

        Corriente.setBackground(new java.awt.Color(247, 247, 247));
        Corriente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        IconCorriente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconoAhorros2.PNG"))); // NOI18N
        IconCorriente.setText("jLabel1");

        CC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CC.setText("CUENTA CORRIENTE");

        SaldoD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SaldoD.setText("Saldo DIsponible");

        javax.swing.GroupLayout CorrienteLayout = new javax.swing.GroupLayout(Corriente);
        Corriente.setLayout(CorrienteLayout);
        CorrienteLayout.setHorizontalGroup(
            CorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorrienteLayout.createSequentialGroup()
                .addComponent(IconCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaldoD, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        CorrienteLayout.setVerticalGroup(
            CorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorrienteLayout.createSequentialGroup()
                .addGroup(CorrienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconCorriente)
                    .addGroup(CorrienteLayout.createSequentialGroup()
                        .addComponent(CC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoD)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        Ahorros.setBackground(new java.awt.Color(247, 247, 247));
        Ahorros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        IconAhorros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconoAhorros.PNG"))); // NOI18N
        IconAhorros.setText("jLabel2");

        CA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CA.setText("CUENTA AHORROS");

        SaldoA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SaldoA.setText("Saldo Disponible");

        javax.swing.GroupLayout AhorrosLayout = new javax.swing.GroupLayout(Ahorros);
        Ahorros.setLayout(AhorrosLayout);
        AhorrosLayout.setHorizontalGroup(
            AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AhorrosLayout.createSequentialGroup()
                .addComponent(IconAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CA, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaldoA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 188, Short.MAX_VALUE))
        );
        AhorrosLayout.setVerticalGroup(
            AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AhorrosLayout.createSequentialGroup()
                .addGroup(AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IconAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SaldoA))
                    .addComponent(CA))
                .addGap(0, 72, Short.MAX_VALUE))
        );

        TarjetaCredito.setBackground(new java.awt.Color(255, 255, 255));
        TarjetaCredito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        IconCreditCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconoCreditCard.png"))); // NOI18N
        IconCreditCard.setText("jLabel1");

        TC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TC.setText("TARJETA DE CRÉDITO");

        SaldoTC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SaldoTC.setText("Saldo Disponible");

        javax.swing.GroupLayout TarjetaCreditoLayout = new javax.swing.GroupLayout(TarjetaCredito);
        TarjetaCredito.setLayout(TarjetaCreditoLayout);
        TarjetaCreditoLayout.setHorizontalGroup(
            TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                .addComponent(IconCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaldoTC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 189, Short.MAX_VALUE))
        );
        TarjetaCreditoLayout.setVerticalGroup(
            TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                .addGroup(TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconCreditCard)
                    .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                        .addComponent(TC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoTC)))
                .addGap(0, 85, Short.MAX_VALUE))
        );

        Transferencias.setBackground(new java.awt.Color(255, 255, 255));
        Transferencias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        Transferenciastxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Transferenciastxt.setText("        TRANSFERENCIAS");

        javax.swing.GroupLayout TransferenciasLayout = new javax.swing.GroupLayout(Transferencias);
        Transferencias.setLayout(TransferenciasLayout);
        TransferenciasLayout.setHorizontalGroup(
            TransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferenciasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Transferenciastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransferenciasLayout.setVerticalGroup(
            TransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferenciasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Transferenciastxt)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TransferenciasInt.setBackground(new java.awt.Color(255, 255, 255));
        TransferenciasInt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        Internacionales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Internacionales.setText("TRANSFERENCIAS INTERNACIONALES");

        javax.swing.GroupLayout TransferenciasIntLayout = new javax.swing.GroupLayout(TransferenciasInt);
        TransferenciasInt.setLayout(TransferenciasIntLayout);
        TransferenciasIntLayout.setHorizontalGroup(
            TransferenciasIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Internacionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TransferenciasIntLayout.setVerticalGroup(
            TransferenciasIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Internacionales, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        TransferenciasNac.setBackground(new java.awt.Color(255, 255, 255));
        TransferenciasNac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        Nacionales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nacionales.setText("TRANSFERENCIAS NACIONALES");

        javax.swing.GroupLayout TransferenciasNacLayout = new javax.swing.GroupLayout(TransferenciasNac);
        TransferenciasNac.setLayout(TransferenciasNacLayout);
        TransferenciasNacLayout.setHorizontalGroup(
            TransferenciasNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nacionales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TransferenciasNacLayout.setVerticalGroup(
            TransferenciasNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nacionales, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PagoLinea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        Pago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pago.setText("PAGO DE SERVICIOS");

        javax.swing.GroupLayout PagoLineaLayout = new javax.swing.GroupLayout(PagoLinea);
        PagoLinea.setLayout(PagoLineaLayout);
        PagoLineaLayout.setHorizontalGroup(
            PagoLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PagoLineaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PagoLineaLayout.setVerticalGroup(
            PagoLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pago, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Cuentas1Layout = new javax.swing.GroupLayout(Cuentas1);
        Cuentas1.setLayout(Cuentas1Layout);
        Cuentas1Layout.setHorizontalGroup(
            Cuentas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cuentas1Layout.createSequentialGroup()
                .addGroup(Cuentas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cuentas1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Corriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cuentas1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(Cuentas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ahorros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TarjetaCredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(Cuentas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TransferenciasInt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transferencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransferenciasNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PagoLinea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        Cuentas1Layout.setVerticalGroup(
            Cuentas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cuentas1Layout.createSequentialGroup()
                .addGroup(Cuentas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cuentas1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Corriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Ahorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(TarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Cuentas1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(Transferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TransferenciasInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TransferenciasNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PagoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jPanel1.add(Cuentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        javax.swing.GroupLayout Contenido1Layout = new javax.swing.GroupLayout(Contenido1);
        Contenido1.setLayout(Contenido1Layout);
        Contenido1Layout.setHorizontalGroup(
            Contenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(Contenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Contenido1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Contenido1Layout.setVerticalGroup(
            Contenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(Contenido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Contenido1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        InterfazPrimaria.add(Contenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 840, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InterfazPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InterfazPrimaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void PrestamosActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }                                         

    private void CuentasMouseEntered(java.awt.event.MouseEvent evt) {                                     
        
    }                                    

    private void CuentasMouseExited(java.awt.event.MouseEvent evt) {                                    
        
    }                                   

    private void CuentasActionPerformed(java.awt.event.ActionEvent evt) {                                        
Cuentas c= new Cuentas();
        c.setSize(840, 600);
        c.setLocation(0, 0);
        
        Contenido1.removeAll();
        Contenido1.add(c, BorderLayout.CENTER);
        Contenido1.revalidate();
        Contenido1.repaint();
    }                                       

    private void PlazoFijoActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Ahorros;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel CA;
    private javax.swing.JLabel CC;
    private javax.swing.JPanel Contenido1;
    private javax.swing.JPanel Corriente;
    private javax.swing.JButton Cuentas;
    private javax.swing.JPanel Cuentas1;
    private javax.swing.JLabel IconAhorros;
    private javax.swing.JLabel IconCorriente;
    private javax.swing.JLabel IconCreditCard;
    private javax.swing.JLabel IconUser;
    private javax.swing.JPanel InterfazPrimaria;
    private javax.swing.JButton Internacionales;
    private javax.swing.JButton Nacionales;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JButton Pago;
    private javax.swing.JPanel PagoLinea;
    private javax.swing.JButton PlazoFijo;
    private javax.swing.JButton Prestamos;
    private javax.swing.JLabel SaldoA;
    private javax.swing.JLabel SaldoD;
    private javax.swing.JLabel SaldoTC;
    private javax.swing.JLabel TC;
    private javax.swing.JPanel TarjetaCredito;
    private javax.swing.JPanel Transferencias;
    private javax.swing.JPanel TransferenciasInt;
    private javax.swing.JPanel TransferenciasNac;
    private javax.swing.JLabel Transferenciastxt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
