/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.Random;
import javax.swing.JTextField;

/**
 *
 * @author TOFIT
 */
public class MenuCuentas extends javax.swing.JFrame {
    /**
     * Creates new form Cuentas
     */
    public MenuCuentas() {
        initComponents();
}
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfazPrimaria = new javax.swing.JPanel();
        PlazoFijo = new javax.swing.JButton();
        Prestamos = new javax.swing.JButton();
        Cuentasboton = new javax.swing.JButton();
        IconUser = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        Cuentas = new javax.swing.JPanel();
        Cuentas3 = new javax.swing.JPanel();
        Corriente2 = new javax.swing.JPanel();
        IconCorriente2 = new javax.swing.JLabel();
        CC2 = new javax.swing.JLabel();
        SaldoD2 = new javax.swing.JLabel();
        Saldoboton1 = new javax.swing.JButton();
        Saldotxt = new javax.swing.JLabel();
        CuentaBoton = new javax.swing.JButton();
        Cuenta1txt = new javax.swing.JLabel();
        Ahorros = new javax.swing.JPanel();
        IconAhorros = new javax.swing.JLabel();
        CA = new javax.swing.JLabel();
        SaldoA = new javax.swing.JLabel();
        Saldoboton2 = new javax.swing.JButton();
        Cuenta2txt = new javax.swing.JLabel();
        CuentaBoton1 = new javax.swing.JButton();
        Saldotxt3 = new javax.swing.JLabel();
        TarjetaCredito = new javax.swing.JPanel();
        IconCreditCard = new javax.swing.JLabel();
        TC = new javax.swing.JLabel();
        SaldoTC = new javax.swing.JLabel();
        Saldoboton3 = new javax.swing.JButton();
        Cuenta3txt = new javax.swing.JLabel();
        CuentaBoton2 = new javax.swing.JButton();
        Saldo1txt = new javax.swing.JLabel();
        Transferencias = new javax.swing.JPanel();
        Transferenciastxt = new javax.swing.JLabel();
        TransferenciasInt = new javax.swing.JPanel();
        Internacionales = new javax.swing.JButton();
        TransferenciasNac = new javax.swing.JPanel();
        Nacionales = new javax.swing.JButton();
        PagoLinea = new javax.swing.JPanel();
        Pago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(840, 600));

        InterfazPrimaria.setBackground(new java.awt.Color(255, 255, 255));
        InterfazPrimaria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlazoFijo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlazoFijo.setForeground(new java.awt.Color(200, 0, 0));
        PlazoFijo.setText("Plazo Fijo");
        PlazoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlazoFijoActionPerformed(evt);
            }
        });
        InterfazPrimaria.add(PlazoFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 280, 50));

        Prestamos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Prestamos.setForeground(new java.awt.Color(204, 0, 0));
        Prestamos.setText("Préstamos");
        Prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestamosActionPerformed(evt);
            }
        });
        InterfazPrimaria.add(Prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 280, 50));

        Cuentasboton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cuentasboton.setForeground(new java.awt.Color(204, 0, 0));
        Cuentasboton.setText("Cuentas");
        Cuentasboton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cuentasboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CuentasbotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CuentasbotonMouseExited(evt);
            }
        });
        Cuentasboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentasbotonActionPerformed(evt);
            }
        });
        InterfazPrimaria.add(Cuentasboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 50));

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconUseer.PNG"))); // NOI18N
        IconUser.setText("IconUser");
        InterfazPrimaria.add(IconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 110));

        Bienvenido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bienvenido.setText("Bienvenido,");
        InterfazPrimaria.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 20));

        NombreUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        NombreUsuario.setText("Pillajo De La Cruz Johan Ariel");
        InterfazPrimaria.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 230, 40));

        Contenido.setBackground(new java.awt.Color(204, 204, 204));

        Cuentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cuentas3.setBackground(new java.awt.Color(204, 204, 204));
        Cuentas3.setPreferredSize(new java.awt.Dimension(840, 600));

        Corriente2.setBackground(new java.awt.Color(247, 247, 247));
        Corriente2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        IconCorriente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconoAhorros2.PNG"))); // NOI18N
        IconCorriente2.setText("jLabel1");

        CC2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CC2.setText("CUENTA CORRIENTE");

        SaldoD2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SaldoD2.setText("Saldo Disponible");

        Saldoboton1.setText("Generar Saldo");
        Saldoboton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saldoboton1ActionPerformed(evt);
            }
        });

        Saldotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Saldotxt.setText("$");

        CuentaBoton.setText("Generar Cuenta");
        CuentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBotonActionPerformed(evt);
            }
        });

        Cuenta1txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cuenta1txt.setText("N°");

        javax.swing.GroupLayout Corriente2Layout = new javax.swing.GroupLayout(Corriente2);
        Corriente2.setLayout(Corriente2Layout);
        Corriente2Layout.setHorizontalGroup(
            Corriente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Corriente2Layout.createSequentialGroup()
                .addComponent(IconCorriente2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Corriente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Corriente2Layout.createSequentialGroup()
                        .addComponent(Saldotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Corriente2Layout.createSequentialGroup()
                        .addGroup(Corriente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CC2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaldoD2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cuenta1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Corriente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Saldoboton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CuentaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))))
        );
        Corriente2Layout.setVerticalGroup(
            Corriente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Corriente2Layout.createSequentialGroup()
                .addGroup(Corriente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconCorriente2)
                    .addGroup(Corriente2Layout.createSequentialGroup()
                        .addComponent(CC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoD2))
                    .addGroup(Corriente2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Saldoboton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Corriente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CuentaBoton)
                            .addComponent(Cuenta1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Saldotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        Ahorros.setBackground(new java.awt.Color(247, 247, 247));
        Ahorros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        IconAhorros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconoAhorros.PNG"))); // NOI18N
        IconAhorros.setText("jLabel2");

        CA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CA.setText("CUENTA AHORROS");

        SaldoA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SaldoA.setText("Saldo Disponible");

        Saldoboton2.setText("Generar Saldo");
        Saldoboton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saldoboton2ActionPerformed(evt);
            }
        });

        Cuenta2txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cuenta2txt.setText("N°");

        CuentaBoton1.setText("Generar Cuenta");
        CuentaBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBoton1ActionPerformed(evt);
            }
        });

        Saldotxt3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Saldotxt3.setText("$");

        javax.swing.GroupLayout AhorrosLayout = new javax.swing.GroupLayout(Ahorros);
        Ahorros.setLayout(AhorrosLayout);
        AhorrosLayout.setHorizontalGroup(
            AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AhorrosLayout.createSequentialGroup()
                .addComponent(IconAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AhorrosLayout.createSequentialGroup()
                        .addComponent(Saldotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AhorrosLayout.createSequentialGroup()
                        .addComponent(Cuenta2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CuentaBoton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(AhorrosLayout.createSequentialGroup()
                        .addGroup(AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CA, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaldoA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addComponent(Saldoboton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );
        AhorrosLayout.setVerticalGroup(
            AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AhorrosLayout.createSequentialGroup()
                .addGroup(AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AhorrosLayout.createSequentialGroup()
                        .addComponent(CA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IconAhorros)
                        .addComponent(Saldoboton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cuenta2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuentaBoton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Saldotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        TarjetaCredito.setBackground(new java.awt.Color(255, 255, 255));
        TarjetaCredito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        IconCreditCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconoCreditCard.png"))); // NOI18N
        IconCreditCard.setText("jLabel1");

        TC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TC.setText("TARJETA DE CRÉDITO");

        SaldoTC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SaldoTC.setText("Saldo Disponible");

        Saldoboton3.setText("Generar Saldo");
        Saldoboton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saldoboton3ActionPerformed(evt);
            }
        });

        Cuenta3txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cuenta3txt.setText("N°");

        CuentaBoton2.setText("Generar Cuenta");
        CuentaBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBoton2ActionPerformed(evt);
            }
        });

        Saldo1txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Saldo1txt.setText("$");

        javax.swing.GroupLayout TarjetaCreditoLayout = new javax.swing.GroupLayout(TarjetaCredito);
        TarjetaCredito.setLayout(TarjetaCreditoLayout);
        TarjetaCreditoLayout.setHorizontalGroup(
            TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                .addComponent(IconCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                        .addComponent(Saldo1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                        .addComponent(Cuenta3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CuentaBoton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                        .addGroup(TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaldoTC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addComponent(Saldoboton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );
        TarjetaCreditoLayout.setVerticalGroup(
            TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                .addGroup(TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconCreditCard)
                    .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                        .addComponent(TC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoTC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TarjetaCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cuenta3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuentaBoton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Saldo1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
            .addGroup(TarjetaCreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Saldoboton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Transferencias.setBackground(new java.awt.Color(255, 255, 255));
        Transferencias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        Transferenciastxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Transferenciastxt.setText("        TRANSFERENCIAS");

        javax.swing.GroupLayout TransferenciasLayout = new javax.swing.GroupLayout(Transferencias);
        Transferencias.setLayout(TransferenciasLayout);
        TransferenciasLayout.setHorizontalGroup(
            TransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferenciasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Transferenciastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransferenciasLayout.setVerticalGroup(
            TransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferenciasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Transferenciastxt)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TransferenciasInt.setBackground(new java.awt.Color(255, 255, 255));
        TransferenciasInt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        Internacionales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Internacionales.setText("TRANSFERENCIAS INTERNACIONALES");
        Internacionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternacionalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransferenciasIntLayout = new javax.swing.GroupLayout(TransferenciasInt);
        TransferenciasInt.setLayout(TransferenciasIntLayout);
        TransferenciasIntLayout.setHorizontalGroup(
            TransferenciasIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Internacionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TransferenciasIntLayout.setVerticalGroup(
            TransferenciasIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Internacionales, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        TransferenciasNac.setBackground(new java.awt.Color(255, 255, 255));
        TransferenciasNac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        Nacionales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nacionales.setText("TRANSFERENCIAS NACIONALES");
        Nacionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacionalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransferenciasNacLayout = new javax.swing.GroupLayout(TransferenciasNac);
        TransferenciasNac.setLayout(TransferenciasNacLayout);
        TransferenciasNacLayout.setHorizontalGroup(
            TransferenciasNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nacionales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TransferenciasNacLayout.setVerticalGroup(
            TransferenciasNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nacionales, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PagoLinea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        Pago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pago.setText("PAGO DE SERVICIOS");
        Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PagoLineaLayout = new javax.swing.GroupLayout(PagoLinea);
        PagoLinea.setLayout(PagoLineaLayout);
        PagoLineaLayout.setHorizontalGroup(
            PagoLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PagoLineaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PagoLineaLayout.setVerticalGroup(
            PagoLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pago, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Cuentas3Layout = new javax.swing.GroupLayout(Cuentas3);
        Cuentas3.setLayout(Cuentas3Layout);
        Cuentas3Layout.setHorizontalGroup(
            Cuentas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cuentas3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cuentas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Corriente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ahorros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TarjetaCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(Cuentas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TransferenciasInt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transferencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransferenciasNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PagoLinea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        Cuentas3Layout.setVerticalGroup(
            Cuentas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cuentas3Layout.createSequentialGroup()
                .addGroup(Cuentas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cuentas3Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(Transferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TransferenciasInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TransferenciasNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PagoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Cuentas3Layout.createSequentialGroup()
                        .addComponent(Corriente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ahorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Cuentas.add(Cuentas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        InterfazPrimaria.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 840, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InterfazPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InterfazPrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrestamosActionPerformed(ActionEvent evt) {//GEN-FIRST:event_PrestamosActionPerformed
         Prestamos pre= new Prestamos();
         pre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_PrestamosActionPerformed

    private void CuentasbotonMouseEntered(MouseEvent evt) {//GEN-FIRST:event_CuentasbotonMouseEntered
        
    }//GEN-LAST:event_CuentasbotonMouseEntered

    private void CuentasbotonMouseExited(MouseEvent evt) {//GEN-FIRST:event_CuentasbotonMouseExited
        
    }//GEN-LAST:event_CuentasbotonMouseExited

    private void CuentasbotonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_CuentasbotonActionPerformed

    }//GEN-LAST:event_CuentasbotonActionPerformed

    private void PlazoFijoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_PlazoFijoActionPerformed
     PlazoFijo pre= new PlazoFijo();
         pre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_PlazoFijoActionPerformed

    private void Saldoboton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_Saldoboton2ActionPerformed
       double n2 = (int)(Math.random()*10000+1);
        Saldotxt3.setText(Saldotxt3.getText() + " " + n2 );
    }//GEN-LAST:event_Saldoboton2ActionPerformed

    private void InternacionalesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_InternacionalesActionPerformed
     TransferenciasInt pre= new TransferenciasInt();
        pre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_InternacionalesActionPerformed

    private void NacionalesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_NacionalesActionPerformed
         TransferenciasNac pre= new TransferenciasNac();
        pre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_NacionalesActionPerformed

    private void PagoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_PagoActionPerformed
         PagoServicios pre= new PagoServicios();
        pre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_PagoActionPerformed

    private void Saldoboton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_Saldoboton1ActionPerformed

 double n1 = (int)(Math.random()*10000+1);
        Saldotxt.setText(Saldotxt.getText() + " " + n1 );
        
    }//GEN-LAST:event_Saldoboton1ActionPerformed

    private void Saldoboton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saldoboton3ActionPerformed
       double n1 = (int)(Math.random()*10000+1);
        Saldo1txt.setText(Saldo1txt.getText() + " " + n1 );
    }//GEN-LAST:event_Saldoboton3ActionPerformed

    private void CuentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBotonActionPerformed

      int n1 = (int)(Math.random()*100000000+12345678);
        Cuenta1txt.setText(Cuenta1txt.getText() +" " + n1 );        
    }//GEN-LAST:event_CuentaBotonActionPerformed

    private void CuentaBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBoton1ActionPerformed
      int n1 = (int)(Math.random()*100000000+12345678);
        Cuenta2txt.setText(Cuenta2txt.getText() +" " + n1 );
    }//GEN-LAST:event_CuentaBoton1ActionPerformed

    private void CuentaBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBoton2ActionPerformed
      int n1 = (int)(Math.random()*100000000+12345678);
        Cuenta3txt.setText(Cuenta3txt.getText() +" " + n1 );
    }//GEN-LAST:event_CuentaBoton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ahorros;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel CA;
    private javax.swing.JLabel CC2;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Corriente2;
    private javax.swing.JLabel Cuenta1txt;
    private javax.swing.JLabel Cuenta2txt;
    private javax.swing.JLabel Cuenta3txt;
    private javax.swing.JButton CuentaBoton;
    private javax.swing.JButton CuentaBoton1;
    private javax.swing.JButton CuentaBoton2;
    private javax.swing.JPanel Cuentas;
    private javax.swing.JPanel Cuentas3;
    private javax.swing.JButton Cuentasboton;
    private javax.swing.JLabel IconAhorros;
    private javax.swing.JLabel IconCorriente2;
    private javax.swing.JLabel IconCreditCard;
    private javax.swing.JLabel IconUser;
    private javax.swing.JPanel InterfazPrimaria;
    private javax.swing.JButton Internacionales;
    private javax.swing.JButton Nacionales;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JButton Pago;
    private javax.swing.JPanel PagoLinea;
    private javax.swing.JButton PlazoFijo;
    private javax.swing.JButton Prestamos;
    private javax.swing.JLabel Saldo1txt;
    private javax.swing.JLabel SaldoA;
    private javax.swing.JLabel SaldoD2;
    private javax.swing.JLabel SaldoTC;
    private javax.swing.JButton Saldoboton1;
    private javax.swing.JButton Saldoboton2;
    private javax.swing.JButton Saldoboton3;
    private javax.swing.JLabel Saldotxt;
    private javax.swing.JLabel Saldotxt3;
    private javax.swing.JLabel TC;
    private javax.swing.JPanel TarjetaCredito;
    private javax.swing.JPanel Transferencias;
    private javax.swing.JPanel TransferenciasInt;
    private javax.swing.JPanel TransferenciasNac;
    private javax.swing.JLabel Transferenciastxt;
    // End of variables declaration//GEN-END:variables

    private JTextField generarAleatorio(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
