/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import javax.swing.JOptionPane;

/**
 *
 * @author TOFIT
 */
public class PagoServicios extends javax.swing.JFrame {

    /**
     * Creates new form PagoServicios
     */
    public PagoServicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IconUser = new javax.swing.JLabel();
        returnboton = new javax.swing.JButton();
        Bienvenido = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Logotxt = new javax.swing.JLabel();
        Serviciotxt = new javax.swing.JLabel();
        SeleServ = new javax.swing.JComboBox<>();
        Cantidadtxt = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        Cedulatxt = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        IconoAgua = new javax.swing.JLabel();
        IconoInternet = new javax.swing.JLabel();
        IconoLuz = new javax.swing.JLabel();
        IconoTelefono = new javax.swing.JLabel();
        Pagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconUseer.PNG"))); // NOI18N
        IconUser.setText("IconUser");

        returnboton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        returnboton.setForeground(new java.awt.Color(204, 0, 0));
        returnboton.setText("REGRESAR");
        returnboton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        returnboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbotonActionPerformed(evt);
            }
        });

        Bienvenido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bienvenido.setText("Bienvenido,");

        NombreUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        NombreUsuario.setText("Pillajo De La Cruz Johan Ariel");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Pago de Servicios");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        Logotxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(Logotxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Logotxt)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 337, 840, -1));

        Serviciotxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Serviciotxt.setForeground(new java.awt.Color(204, 0, 0));
        Serviciotxt.setText("Servicio:");
        jPanel2.add(Serviciotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, -1, -1));

        SeleServ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeleServ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Agua", "Luz", "Teléfono", "Internet" }));
        jPanel2.add(SeleServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 76, 104, -1));

        Cantidadtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cantidadtxt.setForeground(new java.awt.Color(204, 0, 0));
        Cantidadtxt.setText("Cantidad:");
        jPanel2.add(Cantidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, -1, -1));

        Cantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadKeyTyped(evt);
            }
        });
        jPanel2.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 124, 101, -1));

        Cedulatxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cedulatxt.setForeground(new java.awt.Color(204, 0, 0));
        Cedulatxt.setText("Cédula:");
        jPanel2.add(Cedulatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 77, -1, -1));

        Cedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });
        jPanel2.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 76, 116, -1));

        IconoAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/iconoAgua.png"))); // NOI18N
        jPanel2.add(IconoAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 110));

        IconoInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/internetIcono.png"))); // NOI18N
        jPanel2.add(IconoInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        IconoLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LuzIcono.png"))); // NOI18N
        IconoLuz.setText("jLabel5");
        jPanel2.add(IconoLuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 110, 130));

        IconoTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconoTelefono.png"))); // NOI18N
        jPanel2.add(IconoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 120, 120));

        Pagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pagar.setForeground(new java.awt.Color(204, 0, 0));
        Pagar.setText("PAGAR");
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });
        jPanel2.add(Pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnboton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnboton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbotonActionPerformed
        MenuCuentas pre= new MenuCuentas();
        pre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnbotonActionPerformed

    private void CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyTyped
     char validar=evt.getKeyChar();
     if (Character.isLetter(validar)){
         getToolkit().beep();
         evt.consume();
         
         JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
     }
    }//GEN-LAST:event_CantidadKeyTyped

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
             char validar=evt.getKeyChar();
     if (Character.isLetter(validar)){
         getToolkit().beep();
         evt.consume();
         
         JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
     }
    }//GEN-LAST:event_CedulaKeyTyped

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
         JOptionPane.showMessageDialog(this," PAGO REALIZADO");
       Cedula.setText("");
       Cantidad.setText(null);
    }//GEN-LAST:event_PagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JLabel Cantidadtxt;
    private javax.swing.JTextField Cedula;
    private javax.swing.JLabel Cedulatxt;
    private javax.swing.JLabel IconUser;
    private javax.swing.JLabel IconoAgua;
    private javax.swing.JLabel IconoInternet;
    private javax.swing.JLabel IconoLuz;
    private javax.swing.JLabel IconoTelefono;
    private javax.swing.JLabel Logotxt;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JButton Pagar;
    private javax.swing.JComboBox<String> SeleServ;
    private javax.swing.JLabel Serviciotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton returnboton;
    // End of variables declaration//GEN-END:variables
}
