/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;

/**
 *
 * @author TOFIT
 */
public class Prestamos extends javax.swing.JFrame {

    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
                  this.ListaCantidad.addItemListener(new ItemListener(){
          public void itemStateChanged(ItemEvent e){
             if (e.getStateChange()== ItemEvent.SELECTED){
                 switch(e.getItem().toString()){
                      case "-Seleccionar-":
                     InteresValor.setText("");
                     break;
                     case "1000":
                     InteresValor.setText("1");
                     break;
                     
                     case "1500":
                     InteresValor.setText("1");
                     break;
                     
                     case "2500":
                     InteresValor.setText("3");
                     break;
                      case "4000":
                     InteresValor.setText("4");
                     break;
                      case "6000":
                     InteresValor.setText("6");
                     break;
                
                  }
                 }
                 }
          });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        IconUser = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        Prestamospanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cantidadtxt = new javax.swing.JLabel();
        ListaCantidad = new javax.swing.JComboBox<>();
        Cuentatxt = new javax.swing.JLabel();
        ListaCuentas = new javax.swing.JComboBox<>();
        SimboloDinero = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        Interestxt = new javax.swing.JLabel();
        InteresValor = new javax.swing.JTextField();
        SimboloPorcentaje = new javax.swing.JLabel();
        GuiaPrestamos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        returnboton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Datos.setBackground(new java.awt.Color(255, 255, 255));

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/IconUseer.PNG"))); // NOI18N
        IconUser.setText("IconUser");

        Bienvenido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bienvenido.setText("Bienvenido,");

        NombreUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        NombreUsuario.setText("Pillajo De La Cruz Johan Ariel");

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        Prestamospanel.setBackground(new java.awt.Color(255, 255, 255));
        Prestamospanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Prestamos");

        javax.swing.GroupLayout PrestamospanelLayout = new javax.swing.GroupLayout(Prestamospanel);
        Prestamospanel.setLayout(PrestamospanelLayout);
        PrestamospanelLayout.setHorizontalGroup(
            PrestamospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrestamospanelLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel1)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        PrestamospanelLayout.setVerticalGroup(
            PrestamospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrestamospanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Cantidadtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cantidadtxt.setForeground(new java.awt.Color(204, 0, 0));
        Cantidadtxt.setText("Cantidad:");

        ListaCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "1000", "1500", "2500", "4000", "6000" }));
        ListaCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCantidadActionPerformed(evt);
            }
        });

        Cuentatxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cuentatxt.setForeground(new java.awt.Color(204, 0, 0));
        Cuentatxt.setText("Cuenta:");

        ListaCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Cuenta Ahorros", "Cuenta Corriente" }));

        SimboloDinero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SimboloDinero.setForeground(new java.awt.Color(204, 0, 0));
        SimboloDinero.setText("$");

        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(204, 0, 0));
        Aceptar.setText("ACEPTAR");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Interestxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Interestxt.setForeground(new java.awt.Color(204, 0, 0));
        Interestxt.setText("Interés:");

        InteresValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InteresValorActionPerformed(evt);
            }
        });

        SimboloPorcentaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SimboloPorcentaje.setForeground(new java.awt.Color(204, 0, 0));
        SimboloPorcentaje.setText("%");

        GuiaPrestamos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GuiaPrestamos.setText("<html> <b><p>PRESTAMOS CON TASA DE INTERESES BAJOS.<b> <p>  "
            + "Gracias a nuestra tasa de interés más baja del mercado, usted finalmente podrá hacerlos prestamos que usted desee, sin el riesgo de pagar muchos intereses. "
            + "<p>Esto va a lograr que usted, y su familia, puedan comprar un carro, una casa o financiar<p>"
            + " la Universidad de su hijx.   <p>CON NOSOTROS, SUS SUEÑOS SE CUMPLEN. <p> <html>");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/FamiliaFelizPrestamos.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Prestamospanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cuentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Interestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cantidadtxt))
                                .addGap(56, 56, 56)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ListaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Aceptar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ListaCuentas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InteresValor, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SimboloDinero)
                            .addComponent(SimboloPorcentaje)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(GuiaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(Prestamospanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cantidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SimboloDinero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cuentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Interestxt)
                            .addComponent(InteresValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SimboloPorcentaje))
                        .addGap(18, 18, 18)
                        .addComponent(Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GuiaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        returnboton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        returnboton.setForeground(new java.awt.Color(204, 0, 0));
        returnboton.setText("REGRESAR");
        returnboton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        returnboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnboton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnboton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbotonActionPerformed
  MenuCuentas pre= new MenuCuentas();
         pre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_returnbotonActionPerformed

    private void ListaCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaCantidadActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
         JOptionPane.showMessageDialog(this," Préstamo realizado");
    }//GEN-LAST:event_AceptarActionPerformed

    private void InteresValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InteresValorActionPerformed

    }//GEN-LAST:event_InteresValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Cantidadtxt;
    private javax.swing.JLabel Cuentatxt;
    private javax.swing.JPanel Datos;
    private javax.swing.JLabel GuiaPrestamos;
    private javax.swing.JLabel IconUser;
    private javax.swing.JTextField InteresValor;
    private javax.swing.JLabel Interestxt;
    private javax.swing.JComboBox<String> ListaCantidad;
    private javax.swing.JComboBox<String> ListaCuentas;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel Prestamospanel;
    private javax.swing.JLabel SimboloDinero;
    private javax.swing.JLabel SimboloPorcentaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton returnboton;
    // End of variables declaration//GEN-END:variables

}
